apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: cloud.ionos.com
    creationTimestamp: "2022-09-10T10:40:51Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/cloud-ionos-com
    - external-provisioner.volume.kubernetes.io/finalizer
    name: pvc-11d8962a-309b-44db-925f-4bf2a633d604
    resourceVersion: "30296192274"
    uid: 99924193-bc95-4987-b7c4-cea5d9dae68c
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: mongo-pvc-logging
      namespace: default
      resourceVersion: "1946634627"
      uid: 11d8962a-309b-44db-925f-4bf2a633d604
    csi:
      driver: cloud.ionos.com
      fsType: ext4
      volumeAttributes:
        capacityBytes: "5368709120"
        datacenterID: bd5af478-76ac-4268-8fa7-7ae82b0abbba
        noformat: "false"
        storage.kubernetes.io/csiProvisionerIdentity: 1658338651414-8081-cloud.ionos.com
      volumeHandle: datacenters/bd5af478-76ac-4268-8fa7-7ae82b0abbba/volumes/9c4f78b5-9b25-4990-9c55-1938f41210d8
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: enterprise.cloud.ionos.com/datacenter-id
            operator: In
            values:
            - bd5af478-76ac-4268-8fa7-7ae82b0abbba
    persistentVolumeReclaimPolicy: Delete
    storageClassName: ionos-enterprise-ssd
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: cloud.ionos.com
    creationTimestamp: "2022-09-10T10:32:53Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/cloud-ionos-com
    - external-provisioner.volume.kubernetes.io/finalizer
    name: pvc-18b74c40-d245-444f-9315-1368f7f15aba
    resourceVersion: "30296192275"
    uid: df65ee9f-4816-4500-bd5f-5e6973e6e83d
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: mongo-pvc-app
      namespace: default
      resourceVersion: "1946583340"
      uid: 18b74c40-d245-444f-9315-1368f7f15aba
    csi:
      driver: cloud.ionos.com
      fsType: ext4
      volumeAttributes:
        capacityBytes: "5368709120"
        datacenterID: bd5af478-76ac-4268-8fa7-7ae82b0abbba
        noformat: "false"
        storage.kubernetes.io/csiProvisionerIdentity: 1658338651414-8081-cloud.ionos.com
      volumeHandle: datacenters/bd5af478-76ac-4268-8fa7-7ae82b0abbba/volumes/fe276a05-bf79-4d91-8e0a-99791574b457
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: enterprise.cloud.ionos.com/datacenter-id
            operator: In
            values:
            - bd5af478-76ac-4268-8fa7-7ae82b0abbba
    persistentVolumeReclaimPolicy: Delete
    storageClassName: ionos-enterprise-ssd
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
