apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 0a4c731c97c646c9811de6c12f70fd2e5b20f75786e7e9458bc045c8394617ff
      cni.projectcalico.org/podIP: 10.221.161.95/32
      cni.projectcalico.org/podIPs: 10.221.161.95/32
      kubectl.kubernetes.io/restartedAt: "2023-06-11T16:31:31+02:00"
    creationTimestamp: "2023-08-17T13:05:26Z"
    generateName: lessony-db4b9dd86-
    labels:
      app: lessony
      pod-template-hash: db4b9dd86
    name: lessony-db4b9dd86-kdxj9
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: lessony-db4b9dd86
      uid: 08e5e8fa-4074-403a-b1cb-6ddeddfe9b6d
    resourceVersion: "33676089308"
    uid: fe054df3-1d9b-4953-834e-e43e18c77abd
  spec:
    containers:
    - env:
      - name: SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            key: smtp-username
            name: secret
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            key: smtp-password
            name: secret
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            key: jwt-secret
            name: secret
      - name: MONGO_URI_LOGGING
        valueFrom:
          secretKeyRef:
            key: mongo-uri-logging
            name: secret
      - name: MONGO_URI
        valueFrom:
          secretKeyRef:
            key: mongo-uri
            name: secret
      - name: SMTP_HOST
        valueFrom:
          configMapKeyRef:
            key: smtp-host
            name: config-map
      - name: SMTP_PORT
        valueFrom:
          configMapKeyRef:
            key: smtp-port
            name: config-map
      - name: EMAIL_FROM
        valueFrom:
          configMapKeyRef:
            key: email-from
            name: config-map
      - name: APP_PORT
        value: "8080"
      - name: APP_PREFIX_PATH
        value: /api/v1
      image: kylecode/lessony:production
      imagePullPolicy: Always
      name: lessony
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-hfnhx
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    imagePullSecrets:
    - name: regcred
    nodeName: prod-pool-1-qimbesl2hn
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-hfnhx
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-08-17T13:05:26Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-08-17T13:07:06Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-08-17T13:07:06Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-08-17T13:05:26Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://4dd1b90938b4e84778d9add22ac688417a4a54c69986642f62cef374cd30fa25
      image: docker.io/kylecode/lessony:production
      imageID: docker.io/kylecode/lessony@sha256:fbf591a46505c751b43c15fbe077fb5724d324a8c4435dbe37bb332f2f4cb10d
      lastState:
        terminated:
          containerID: containerd://b00ad6ed2287e8901dcb9cea6c42f12bec577bb6035a4e27fe6579ddda0a0d72
          exitCode: 0
          finishedAt: "2023-08-17T13:07:03Z"
          reason: Completed
          startedAt: "2023-08-17T13:05:30Z"
      name: lessony
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: "2023-08-17T13:07:05Z"
    hostIP: 85.215.218.9
    phase: Running
    podIP: 10.221.161.95
    podIPs:
    - ip: 10.221.161.95
    qosClass: BestEffort
    startTime: "2023-08-17T13:05:26Z"
kind: List
metadata:
  resourceVersion: ""
